apiVersion: v1
kind: Service
metadata:
  name: nested-pos
  namespace: clearpath
  labels:
    app: nested-pos
spec:
  selector:
    app: nested-pos
  ports:
    - name: http
      port: 9001
      targetPort: 9001
