apiVersion: v1
kind: Service
metadata:
  name: storefront-api
  namespace: clearpath
  labels:
    app: storefront-api
spec:
  selector:
    app: storefront-api
  ports:
    - name: http
      port: 8085
      targetPort: 8085
