apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-service
  namespace: clearpath
  labels:
    app: availability-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: availability-service
  template:
    metadata:
      labels:
        app: availability-service
    spec:
      containers:
        - name: availability-service
          image: availability-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: clearpath-config
            - configMapRef:
                name: availability-service-config
            - secretRef:
                name: clearpath-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /ready
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
