apiVersion: v1
kind: Service
metadata:
  name: flat-pos
  namespace: clearpath
  labels:
    app: flat-pos
spec:
  selector:
    app: flat-pos
  ports:
    - name: http
      port: 9002
      targetPort: 9002
