apiVersion: v1
kind: Service
metadata:
  name: trace-collector
  namespace: clearpath
  labels:
    app: trace-collector
spec:
  selector:
    app: trace-collector
  ports:
    - name: http
      port: 8084
      targetPort: 8084
